"""B7 gap 1: provenance must describe the run that actually happened.

These tests assert the WRITE path (run -> artifact), not the read path
(artifact -> page). B7's first attempt satisfied a read-path assertion by moving
the constants from review.py into extract.py, where they are stamped into every
artifact unconditionally. Do not edit this file to make it pass.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path
from typing import Any

import pytest

from v2.src.extract import run_episode_extraction

ROOT_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = ROOT_DIR.parent
EPISODE = "00251a80c868f535"
RUBRIC_REL = "v2/docs/design_claim_rubric.md"


class StubExtractor:
    """Records what it was constructed with; emits a fixed verdict.

    Legitimate here because the property under test is what gets RECORDED,
    never what the model decides.
    """

    def __init__(self, model_id: str, runtime: str, quantisation: str) -> None:
        self.model_id = model_id
        self.runtime = runtime
        self.quantisation = quantisation
        self.calls = 0

    def extract_turn(
        self,
        prompt: str,
        target_turn: dict[str, Any],
        context_turn: dict[str, Any] | None = None,
        max_tokens: int = 150,
    ) -> dict[str, Any]:
        self.calls += 1
        return {
            "turn_id": target_turn["turn_id"],
            "verdict": "exclusion",
            "gate_failed": "gate_1",
            "reason": "stub",
        }


def _run(tmp_path: Path, model_id: str, runtime: str, quantisation: str) -> dict[str, Any]:
    stub = StubExtractor(model_id, runtime, quantisation)
    result = run_episode_extraction(
        source_id=EPISODE,
        max_turns=2,
        extractor=stub,
        output_dir=tmp_path,
    )
    assert stub.calls == 2, "the injected extractor was not the one used"
    return result


def test_two_models_record_two_identities(tmp_path: Path) -> None:
    """(c): called twice with two different models, the artifacts differ.

    One call cannot demonstrate this -- a constant and a correct reading are
    identical when only one value has ever existed.
    """
    a = _run(tmp_path / "a", "lab-a/model-a", "ollama", "Q4_K_M")
    b = _run(tmp_path / "b", "lab-b/model-b", "mlx_lm", "8-bit")

    assert a["model_id"] == "lab-a/model-a"
    assert b["model_id"] == "lab-b/model-b"
    assert a["model_id"] != b["model_id"]

    assert a["runtime"] == "ollama"
    assert b["runtime"] == "mlx_lm"
    assert a["runtime"] != b["runtime"]

    assert a["quantisation"] == "Q4_K_M"
    assert b["quantisation"] == "8-bit"
    assert a["quantisation"] != b["quantisation"]


def test_recorded_identity_survives_to_disk(tmp_path: Path) -> None:
    """The artifact on disk carries the same identity the return value claims."""
    a = _run(tmp_path, "lab-c/model-c", "vllm", "fp16")
    written = list(tmp_path.glob("*extraction_*.json"))
    assert len(written) == 1, f"expected exactly one artifact, got {written}"
    on_disk = json.loads(written[0].read_text(encoding="utf-8"))
    for field in ("model_id", "runtime", "quantisation"):
        assert on_disk[field] == a[field], f"{field} differs between return value and disk"
    assert on_disk["model_id"] == "lab-c/model-c"


def test_rubric_commit_is_derived_from_the_rubric_file(tmp_path: Path) -> None:
    """rubric_commit must come from git, not from a literal.

    A commit hash not derived from the file it names is a label, not provenance.
    23da31c is "B1: build turns..." and never touched the rubric.
    """
    expected = subprocess.run(
        ["git", "log", "-1", "--format=%h", "--", RUBRIC_REL],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True,
    ).stdout.strip()
    assert expected, "git returned no commit for the rubric file"

    a = _run(tmp_path, "lab-a/model-a", "ollama", "Q4_K_M")
    assert a["rubric_commit"] == expected, (
        f"recorded {a['rubric_commit']!r}, but the rubric's last commit is {expected!r}"
    )
    assert a["rubric_commit"] != "23da31c", "23da31c never touched the rubric"


def test_decoding_parameters_are_pinned_and_recorded(tmp_path: Path) -> None:
    """Unpinned decoding makes part of B6's measured disagreement sampling noise."""
    a = _run(tmp_path, "lab-a/model-a", "ollama", "Q4_K_M")
    decoding = a.get("decoding")
    assert isinstance(decoding, dict), "artifact records no decoding block"
    for key in ("temperature", "max_tokens"):
        assert key in decoding, f"decoding block does not record {key}"
    assert decoding["temperature"] == 0.0, "decoding must be pinned greedy for reproducibility"


def test_provenance_constants_are_gone_from_extract() -> None:
    """Tripwire, not the assertion: the relocation that already happened once."""
    src = (ROOT_DIR / "src" / "extract.py").read_text(encoding="utf-8")
    for banned in ('RUNTIME = "mlx_lm"', 'QUANTISATION = "4-bit"', 'RUBRIC_COMMIT = "23da31c"'):
        assert banned not in src, f"module-level provenance constant still present: {banned}"


def test_backfilled_artifacts_are_marked_reconstructed() -> None:
    """A backfilled value must be distinguishable from a recorded one."""
    extraction_dir = ROOT_DIR / "artifacts" / "extraction"
    for name in ("rubric_extraction", "falsification_extraction"):
        f = extraction_dir / f"{name}_{EPISODE}.json"
        if not f.exists():
            pytest.skip(f"{f.name} not present")
        d = json.loads(f.read_text(encoding="utf-8"))
        assert d.get("provenance_source") == "reconstructed_b7", (
            f"{f.name} carries hand-backfilled provenance with nothing marking it as such"
        )
